### ISSUE TITLE
Subtitle Tracks from YouTube are named all the same.

### ISSUE THREAD

**Issue by t33st33r** [u8sand/Baka-MPlayer#225]
There is no way to know which subtitle track is which one in YouTube's videos.

This picture tells what i mean: http://imgur.com/fe6zw4W
(Contains a link to a video with a lot of subtitle tracks).
Please, fix it.

PS: Excuse my bad english. This is not my native language.

**Comment by u8sand** [comment]
These things are populated from mpv, so if mpv fixes the support with youtube-dl it should fix itself.

**Comment by godly-devotion** [comment]
I know this is an old issue but you still happen to have the link to the video?
